
FRENCH_SUIT_CARD_RATIO = 54/85
FRENCH_SUIT_CARD_HEIGHT = 321
FRENCH_SUIT_CARD_WIDTH = 205

MAIN_MENU_RATIO = 2/3

NUM_COL_SOLITAIRE = 9
BORDURES_RATIO_SOLITAIRE = 2/10
GAP_RATIO_SOLITAIRE = 2/3
TABLEAUS_PACING = 2/10

GAMES_AVAILABLES = ["Solitaire", "TEST"]
NB_GAMES_AVAILABLES = len(GAMES_AVAILABLES)